name: Workflow to run tests 

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    - name : Run tests 
      run : | 
        pip install -r requirements.txt
        python test_inventory_managment.py